// <auto-generated />
using System;
using BlogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106081327_Create-Database")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogApi.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BlogPost", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Admin Hệ Thống",
                            CategoryId = 1,
                            Content = "Đây là nội dung chi tiết của bài viết về Công Nghệ. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/công nghệ-1.jpg",
                            Title = "Hướng dẫn học Công Nghệ cơ bản phần 1",
                            ViewCount = 8
                        },
                        new
                        {
                            Id = 2,
                            Author = "Admin Hệ Thống",
                            CategoryId = 1,
                            Content = "Đây là nội dung chi tiết của bài viết về Công Nghệ. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/công nghệ-2.jpg",
                            Title = "Hướng dẫn học Công Nghệ cơ bản phần 2",
                            ViewCount = 16
                        },
                        new
                        {
                            Id = 3,
                            Author = "Admin Hệ Thống",
                            CategoryId = 1,
                            Content = "Đây là nội dung chi tiết của bài viết về Công Nghệ. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/công nghệ-3.jpg",
                            Title = "Hướng dẫn học Công Nghệ cơ bản phần 3",
                            ViewCount = 24
                        },
                        new
                        {
                            Id = 4,
                            Author = "Admin Hệ Thống",
                            CategoryId = 2,
                            Content = "Đây là nội dung chi tiết của bài viết về Lập Trình. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/lập trình-1.jpg",
                            Title = "Hướng dẫn học Lập Trình cơ bản phần 1",
                            ViewCount = 32
                        },
                        new
                        {
                            Id = 5,
                            Author = "Admin Hệ Thống",
                            CategoryId = 2,
                            Content = "Đây là nội dung chi tiết của bài viết về Lập Trình. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/lập trình-2.jpg",
                            Title = "Hướng dẫn học Lập Trình cơ bản phần 2",
                            ViewCount = 40
                        },
                        new
                        {
                            Id = 6,
                            Author = "Admin Hệ Thống",
                            CategoryId = 2,
                            Content = "Đây là nội dung chi tiết của bài viết về Lập Trình. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/lập trình-3.jpg",
                            Title = "Hướng dẫn học Lập Trình cơ bản phần 3",
                            ViewCount = 48
                        },
                        new
                        {
                            Id = 7,
                            Author = "Admin Hệ Thống",
                            CategoryId = 3,
                            Content = "Đây là nội dung chi tiết của bài viết về Web Dev. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/web dev-1.jpg",
                            Title = "Hướng dẫn học Web Dev cơ bản phần 1",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 8,
                            Author = "Admin Hệ Thống",
                            CategoryId = 3,
                            Content = "Đây là nội dung chi tiết của bài viết về Web Dev. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/web dev-2.jpg",
                            Title = "Hướng dẫn học Web Dev cơ bản phần 2",
                            ViewCount = 64
                        },
                        new
                        {
                            Id = 9,
                            Author = "Admin Hệ Thống",
                            CategoryId = 3,
                            Content = "Đây là nội dung chi tiết của bài viết về Web Dev. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/web dev-3.jpg",
                            Title = "Hướng dẫn học Web Dev cơ bản phần 3",
                            ViewCount = 72
                        },
                        new
                        {
                            Id = 10,
                            Author = "Admin Hệ Thống",
                            CategoryId = 4,
                            Content = "Đây là nội dung chi tiết của bài viết về Mobile. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/mobile-1.jpg",
                            Title = "Hướng dẫn học Mobile cơ bản phần 1",
                            ViewCount = 80
                        },
                        new
                        {
                            Id = 11,
                            Author = "Admin Hệ Thống",
                            CategoryId = 4,
                            Content = "Đây là nội dung chi tiết của bài viết về Mobile. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/mobile-2.jpg",
                            Title = "Hướng dẫn học Mobile cơ bản phần 2",
                            ViewCount = 88
                        },
                        new
                        {
                            Id = 12,
                            Author = "Admin Hệ Thống",
                            CategoryId = 4,
                            Content = "Đây là nội dung chi tiết của bài viết về Mobile. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/mobile-3.jpg",
                            Title = "Hướng dẫn học Mobile cơ bản phần 3",
                            ViewCount = 96
                        },
                        new
                        {
                            Id = 13,
                            Author = "Admin Hệ Thống",
                            CategoryId = 5,
                            Content = "Đây là nội dung chi tiết của bài viết về DevOps. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/devops-1.jpg",
                            Title = "Hướng dẫn học DevOps cơ bản phần 1",
                            ViewCount = 104
                        },
                        new
                        {
                            Id = 14,
                            Author = "Admin Hệ Thống",
                            CategoryId = 5,
                            Content = "Đây là nội dung chi tiết của bài viết về DevOps. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/devops-2.jpg",
                            Title = "Hướng dẫn học DevOps cơ bản phần 2",
                            ViewCount = 112
                        },
                        new
                        {
                            Id = 15,
                            Author = "Admin Hệ Thống",
                            CategoryId = 5,
                            Content = "Đây là nội dung chi tiết của bài viết về DevOps. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/devops-3.jpg",
                            Title = "Hướng dẫn học DevOps cơ bản phần 3",
                            ViewCount = 120
                        },
                        new
                        {
                            Id = 16,
                            Author = "Admin Hệ Thống",
                            CategoryId = 6,
                            Content = "Đây là nội dung chi tiết của bài viết về AI. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/ai-1.jpg",
                            Title = "Hướng dẫn học AI cơ bản phần 1",
                            ViewCount = 128
                        },
                        new
                        {
                            Id = 17,
                            Author = "Admin Hệ Thống",
                            CategoryId = 6,
                            Content = "Đây là nội dung chi tiết của bài viết về AI. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/ai-2.jpg",
                            Title = "Hướng dẫn học AI cơ bản phần 2",
                            ViewCount = 136
                        },
                        new
                        {
                            Id = 18,
                            Author = "Admin Hệ Thống",
                            CategoryId = 6,
                            Content = "Đây là nội dung chi tiết của bài viết về AI. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/ai-3.jpg",
                            Title = "Hướng dẫn học AI cơ bản phần 3",
                            ViewCount = 144
                        },
                        new
                        {
                            Id = 19,
                            Author = "Admin Hệ Thống",
                            CategoryId = 7,
                            Content = "Đây là nội dung chi tiết của bài viết về Database. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/database-1.jpg",
                            Title = "Hướng dẫn học Database cơ bản phần 1",
                            ViewCount = 152
                        },
                        new
                        {
                            Id = 20,
                            Author = "Admin Hệ Thống",
                            CategoryId = 7,
                            Content = "Đây là nội dung chi tiết của bài viết về Database. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/database-2.jpg",
                            Title = "Hướng dẫn học Database cơ bản phần 2",
                            ViewCount = 160
                        },
                        new
                        {
                            Id = 21,
                            Author = "Admin Hệ Thống",
                            CategoryId = 7,
                            Content = "Đây là nội dung chi tiết của bài viết về Database. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/database-3.jpg",
                            Title = "Hướng dẫn học Database cơ bản phần 3",
                            ViewCount = 168
                        },
                        new
                        {
                            Id = 22,
                            Author = "Admin Hệ Thống",
                            CategoryId = 8,
                            Content = "Đây là nội dung chi tiết của bài viết về Cloud. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/cloud-1.jpg",
                            Title = "Hướng dẫn học Cloud cơ bản phần 1",
                            ViewCount = 176
                        },
                        new
                        {
                            Id = 23,
                            Author = "Admin Hệ Thống",
                            CategoryId = 8,
                            Content = "Đây là nội dung chi tiết của bài viết về Cloud. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/cloud-2.jpg",
                            Title = "Hướng dẫn học Cloud cơ bản phần 2",
                            ViewCount = 184
                        },
                        new
                        {
                            Id = 24,
                            Author = "Admin Hệ Thống",
                            CategoryId = 8,
                            Content = "Đây là nội dung chi tiết của bài viết về Cloud. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/cloud-3.jpg",
                            Title = "Hướng dẫn học Cloud cơ bản phần 3",
                            ViewCount = 192
                        },
                        new
                        {
                            Id = 25,
                            Author = "Admin Hệ Thống",
                            CategoryId = 9,
                            Content = "Đây là nội dung chi tiết của bài viết về Bảo Mật. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/bảo mật-1.jpg",
                            Title = "Hướng dẫn học Bảo Mật cơ bản phần 1",
                            ViewCount = 200
                        },
                        new
                        {
                            Id = 26,
                            Author = "Admin Hệ Thống",
                            CategoryId = 9,
                            Content = "Đây là nội dung chi tiết của bài viết về Bảo Mật. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/bảo mật-2.jpg",
                            Title = "Hướng dẫn học Bảo Mật cơ bản phần 2",
                            ViewCount = 208
                        },
                        new
                        {
                            Id = 27,
                            Author = "Admin Hệ Thống",
                            CategoryId = 9,
                            Content = "Đây là nội dung chi tiết của bài viết về Bảo Mật. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/bảo mật-3.jpg",
                            Title = "Hướng dẫn học Bảo Mật cơ bản phần 3",
                            ViewCount = 216
                        },
                        new
                        {
                            Id = 28,
                            Author = "Admin Hệ Thống",
                            CategoryId = 10,
                            Content = "Đây là nội dung chi tiết của bài viết về Khác. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/khác-1.jpg",
                            Title = "Hướng dẫn học Khác cơ bản phần 1",
                            ViewCount = 224
                        },
                        new
                        {
                            Id = 29,
                            Author = "Admin Hệ Thống",
                            CategoryId = 10,
                            Content = "Đây là nội dung chi tiết của bài viết về Khác. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/khác-2.jpg",
                            Title = "Hướng dẫn học Khác cơ bản phần 2",
                            ViewCount = 232
                        },
                        new
                        {
                            Id = 30,
                            Author = "Admin Hệ Thống",
                            CategoryId = 10,
                            Content = "Đây là nội dung chi tiết của bài viết về Khác. Nội dung này được biên soạn kỹ lưỡng để đảm bảo dài hơn 50 ký tự nhằm đáp ứng yêu cầu kiểm tra dữ liệu đầu vào của hệ thống.",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            ThumbnailUrl = "https://example.com/images/khác-3.jpg",
                            Title = "Hướng dẫn học Khác cơ bản phần 3",
                            ViewCount = 240
                        });
                });

            modelBuilder.Entity("BlogApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Công Nghệ",
                            Name = "Công Nghệ"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Lập Trình",
                            Name = "Lập Trình"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Web Dev",
                            Name = "Web Dev"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Mobile",
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về DevOps",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về AI",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Database",
                            Name = "Database"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Cloud",
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Bảo Mật",
                            Name = "Bảo Mật"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên mục chia sẻ kiến thức về Khác",
                            Name = "Khác"
                        });
                });

            modelBuilder.Entity("BlogApi.Models.BlogPost", b =>
                {
                    b.HasOne("BlogApi.Models.Category", "Category")
                        .WithMany("Blogposts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogApi.Models.Category", b =>
                {
                    b.Navigation("Blogposts");
                });
#pragma warning restore 612, 618
        }
    }
}
